export default {
  "0058b4c6": [() => import(/* webpackChunkName: "0058b4c6" */ "@generated/docusaurus-plugin-content-docs/default/p/docs-175.json"), "@generated/docusaurus-plugin-content-docs/default/p/docs-175.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/docs-175.json")],
  "0e384e19": [() => import(/* webpackChunkName: "0e384e19" */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "4725e3a9": [() => import(/* webpackChunkName: "4725e3a9" */ "@site/docs/chapter-3-humanoid-robotics-basics.md"), "@site/docs/chapter-3-humanoid-robotics-basics.md", require.resolveWeak("@site/docs/chapter-3-humanoid-robotics-basics.md")],
  "52b760af": [() => import(/* webpackChunkName: "52b760af" */ "@site/docs/chapter-4-ai-robotics-integration.md"), "@site/docs/chapter-4-ai-robotics-integration.md", require.resolveWeak("@site/docs/chapter-4-ai-robotics-integration.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "788f7fb4": [() => import(/* webpackChunkName: "788f7fb4" */ "@site/docs/chapter-1-introduction.md"), "@site/docs/chapter-1-introduction.md", require.resolveWeak("@site/docs/chapter-1-introduction.md")],
  "985ce3c3": [() => import(/* webpackChunkName: "985ce3c3" */ "@site/src/pages/textbook.js"), "@site/src/pages/textbook.js", require.resolveWeak("@site/src/pages/textbook.js")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "b70b368c": [() => import(/* webpackChunkName: "b70b368c" */ "@site/docs/chapter-5-future-of-physical-ai.md"), "@site/docs/chapter-5-future-of-physical-ai.md", require.resolveWeak("@site/docs/chapter-5-future-of-physical-ai.md")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  "f1c9e1af": [() => import(/* webpackChunkName: "f1c9e1af" */ "@site/docs/chapter-2-physical-ai-fundamentals.md"), "@site/docs/chapter-2-physical-ai-fundamentals.md", require.resolveWeak("@site/docs/chapter-2-physical-ai-fundamentals.md")],};
